### ISSUE TITLE
`getBuildChanges` doesn't list multiple builds

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/azure-devops-node-api#515]
### Environment
Node version: v16.14.2
Npm version: 8.5.0
OS and version: GH Codespaces
azure-devops-node-api version: ^11.2.0

### Issue Description
It appears that `getBuildChanges` doesn't list more than one build if a pipeline has multiple resources.

E.g:

<img width="643" alt="Screen Shot 2022-08-17 at 4 24 21 PM" src="https://user-images.githubusercontent.com/7839202/185236602-6bac8236-f734-4da2-a939-46be040bdc48.png">

You can see that our release pipeline consumes 2 builds coming from 2 different repos.

The yaml would be something like that:

``` yaml
resources:
  pipelines:
  - pipeline: infrastructure-build
    source: Pipeline 1
    branch: main
    trigger:
      branches: [
  "main"
]
  - pipeline: onebranch-build
    source: Pipeline 2
    project: xxx
    branch: main
    trigger:
      branches: [
  "main"
]
```

The problem is that it looks like ADO only knows about the "self" repo where the pipeline lives and not the other "input" pipelines.

So when I do a `GET https://dev.azure.com/{organization}/{project}/_apis/build/builds/{buildId}/changes?api-version=7.1-preview.2` it just returns build/commit info about the repo the pipeline lives in, nothing about my other "resources" pipeline.

### Expected behaviour

I'd expect `getBuildChanges` to be able to list all changes, just like the ADO UI does where we see all resource pipelines and all commits / repos that triggered a given build pipeline.

### Actual behaviour

Currently there is apparently no way to get any information about all the resource pipelines, for example commit info which is problematic if you're working with multiple input pipelines like us.

### Steps to reproduce

Create a test yaml pipeline with the yaml sample code above that consumes 2 build pipelines coming from 2 repos.
